const http=require('http'),fs=require('fs'),path=require('path'),WebSocket=require('ws');
const PORT=process.env.PORT||8080,W=1400,H=700,GH=240,GD=75,MAX=12,PT=18,BR=13;
const players=new Map();let nextId=1,score={blue:0,red:0},round=1,mode='normal',end=Date.now()+300000,resetAt=0,resetMsg='';let ball={x:W/2,y:H/2,vx:0,vy:0},last=Date.now();
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
function name(s){return String(s||'Player').replace(/[<>]/g,'').replace(/\s+/g,' ').trim().slice(0,16)||'Player'}
function spawn(p){let bx=p.team==='blue'?W*.22:W*.78;p.x=clamp(bx+(Math.random()-.5)*70,PT,W-PT);p.y=H*.18+Math.random()*H*.64;p.vx=p.vy=0}
function balance(){let a=[...players.values()].sort(()=>Math.random()-.5);a.forEach((p,i)=>p.team=i%2?'red':'blue');a.forEach(spawn)}
function reset(){ball={x:W/2,y:H/2,vx:0,vy:0};players.forEach(spawn)}
function state(){return {type:'state',W,H,goalH:GH,goalDepth:GD,playerR:PT,ballR:BR,score,round,mode,timeLeft:mode==='golden'?0:Math.max(0,(end-Date.now())/1000),message:resetMsg,players:[...players.values()].map(p=>({id:p.id,name:p.name,team:p.team,x:p.x,y:p.y})),ball:{x:ball.x,y:ball.y}}}
function broadcast(){let s=JSON.stringify(state());players.forEach(p=>{if(p.ws.readyState===WebSocket.OPEN)try{p.ws.send(s)}catch{}})}
function finish(winner){let losers=[...players.values()].filter(p=>p.team!==winner).sort(()=>Math.random()-.5);let bc=[...players.values()].filter(p=>p.team==='blue').length,rc=[...players.values()].filter(p=>p.team==='red').length;for(const p of losers){if(winner==='blue'&&bc<6){p.team='blue';bc++}else if(winner==='red'&&rc<6){p.team='red';rc++}else{p.team=winner==='blue'?'red':'blue'}};score={blue:0,red:0};round++;mode='normal';end=Date.now()+300000;resetAt=0;resetMsg='';reset()}
function goal(team){score[team]++;resetAt=Date.now()+1200;resetMsg=team.toUpperCase()+' GOAL!';if(mode==='golden'){resetMsg=team.toUpperCase()+' WINS!';return}if(score[team]>=3){resetAt=Date.now()+1800;resetMsg=team.toUpperCase()+' WINS!'}}
function kick(p){let dx=ball.x-p.x,dy=ball.y-p.y,d=Math.hypot(dx,dy)||1;if(d>PT+BR+34)return;let nx=dx/d,ny=dy/d;ball.x=p.x+nx*(PT+BR);ball.y=p.y+ny*(PT+BR);ball.vx=nx*900+p.vx*.35;ball.vy=ny*900+p.vy*.35}
function collide(p){let dx=ball.x-p.x,dy=ball.y-p.y,d=Math.hypot(dx,dy)||1,min=PT+BR;if(d>=min)return;let nx=dx/d,ny=dy/d,ov=min-d;ball.x+=nx*ov;ball.y+=ny*ov;let rel=(ball.vx-p.vx)*nx+(ball.vy-p.vy)*ny;if(rel<0){let j=-1.88*rel;ball.vx+=nx*j;ball.vy+=ny*j}ball.vx+=nx*1.4;ball.vy+=ny*1.4}
function physics(dt){if(resetAt){if(Date.now()>=resetAt){if(mode==='golden')finish(resetMsg.startsWith('BLUE')?'blue':'red');else if(score.blue>=3||score.red>=3)finish(score.blue>=3?'blue':'red');else{resetAt=0;resetMsg='';reset()}}return}if(mode==='normal'&&Date.now()>=end){mode='golden';score={blue:0,red:0};reset();return}players.forEach(p=>{let ax=(p.input.right?1:0)-(p.input.left?1:0),ay=(p.input.down?1:0)-(p.input.up?1:0);if(ax||ay){let l=Math.hypot(ax,ay);p.vx+=ax/l*900*dt;p.vy+=ay/l*900*dt}else{p.vx*=Math.pow(.84,dt);p.vy*=Math.pow(.84,dt)}let s=Math.hypot(p.vx,p.vy);if(s>330){p.vx=p.vx/s*330;p.vy=p.vy/s*330}p.x=clamp(p.x+p.vx*dt,PT,W-PT);p.y=clamp(p.y+p.vy*dt,PT,H-PT);if(p.input.kick){kick(p);p.input.kick=false}});ball.x+=ball.vx*dt;ball.y+=ball.vy*dt;ball.vx*=Math.pow(.55,dt);ball.vy*=Math.pow(.55,dt);if(ball.y<BR){ball.y=BR;ball.vy=Math.abs(ball.vy)*.78}if(ball.y>H-BR){ball.y=H-BR;ball.vy=-Math.abs(ball.vy)*.78}players.forEach(collide);let g=Math.abs(ball.y-H/2)<GH/2;if(ball.x<-BR&&g)return goal('red');if(ball.x>W+BR&&g)return goal('blue');if(ball.x<BR&&!g){ball.x=BR;ball.vx=Math.abs(ball.vx)*.78}if(ball.x>W-BR&&!g){ball.x=W-BR;ball.vx=-Math.abs(ball.vx)*.78}}
const pub=path.join(__dirname,'public');const server=http.createServer((req,res)=>{let u;try{u=decodeURIComponent((req.url||'/').split('?')[0])}catch{return res.writeHead(400),res.end('Bad request')}if(u==='/')u='/index.html';let f=path.normalize(path.join(pub,u));if(!f.startsWith(pub+path.sep))return res.writeHead(403),res.end('Forbidden');fs.readFile(f,(e,d)=>{if(e)return res.writeHead(404),res.end('Not found');let t=path.extname(f)==='.html'?'text/html':path.extname(f)==='.js'?'text/javascript':'text/plain';res.writeHead(200,{'Content-Type':t+'; charset=utf-8','Cache-Control':'no-store'});res.end(d)})});
const wss=new WebSocket.Server({server});wss.on('connection',ws=>{if(players.size>=MAX){ws.send(JSON.stringify({type:'error',message:'Server đầy! Tối đa 12 người.'}));return ws.close()}let id=String(nextId++),p={id,name:'Player',team:'blue',x:0,y:0,vx:0,vy:0,input:{up:false,down:false,left:false,right:false,kick:false},ws};players.set(id,p);balance();ws.send(JSON.stringify({type:'welcome',id}));broadcast();ws.on('message',raw=>{try{let m=JSON.parse(raw);if(m.type==='name'){p.name=name(m.name);broadcast()}else if(m.type==='input')p.input={up:!!m.up,down:!!m.down,left:!!m.left,right:!!m.right,kick:!!m.kick};else if(m.type==='chat'){let text=String(m.text||'').replace(/[\r\n<>]/g,'').trim().slice(0,80);if(text){let q=JSON.stringify({type:'chat',name:p.name,text});players.forEach(x=>{if(x.ws.readyState===WebSocket.OPEN)try{x.ws.send(q)}catch{}})}}}catch{}});ws.on('close',()=>{players.delete(id);if(players.size)balance();else reset();broadcast()})});
setInterval(()=>{let n=Date.now(),dt=Math.min(.05,(n-last)/1000);last=n;physics(dt);broadcast()},1000/30);server.listen(PORT,'0.0.0.0',()=>console.log('Ball Hax server on '+PORT));
